'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zelo.Luma.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Disabled_iconDarkGear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_iconDarkGear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_iconDarkGearBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_iconDarkGearBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_iconDarkMan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_iconDarkMan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_iconDarkManBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_iconDarkManBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_iconDarkMinus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_iconDarkMinus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_iconDarkMinusBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_iconDarkMinusBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_iconDarkPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_iconDarkPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_iconDarkPlusBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_iconDarkPlusBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_runmodeAutomatic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_runmodeAutomatic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_runmodeAutomaticBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_runmodeAutomaticBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_runmodeManual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_runmodeManual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disabled_runmodeManualBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabled_runmodeManualBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property greenStar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greenStar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkGear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkGear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkGearBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkGearBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkGearMiddle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkGearMiddle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkMan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkMan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkManBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkManBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkManMiddle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkManMiddle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkMinus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkMinus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkMinusBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkMinusBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkMinusMiddle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkMinusMiddle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkPlusBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkPlusBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconDarkPlusMiddle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconDarkPlusMiddle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLightGear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLightGear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLightGearMiddle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLightGearMiddle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLightMan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLightMan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLightManMiddle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLightManMiddle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLightMinus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLightMinus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLightMinusMiddle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLightMinusMiddle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLightPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLightPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconLightPlusMiddle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLightPlusMiddle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redStar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redStar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property runmodeAutomatic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("runmodeAutomatic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property runmodeAutomaticBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("runmodeAutomaticBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property runmodeManual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("runmodeManual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property runmodeManualBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("runmodeManualBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
