'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property GUI_ButtonRadius() As Integer
            Get
                Return CType(Me("GUI_ButtonRadius"),Integer)
            End Get
            Set
                Me("GUI_ButtonRadius") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 51, 204")>  _
        Public Property GUI_ColorSecondary1() As Global.System.Drawing.Color
            Get
                Return CType(Me("GUI_ColorSecondary1"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GUI_ColorSecondary1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 25, 104")>  _
        Public Property GUI_ColorSecondary2() As Global.System.Drawing.Color
            Get
                Return CType(Me("GUI_ColorSecondary2"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GUI_ColorSecondary2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property GUI_ColorPrimary1() As Global.System.Drawing.Color
            Get
                Return CType(Me("GUI_ColorPrimary1"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GUI_ColorPrimary1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 255, 102")>  _
        Public Property GUI_ColorPrimary2() As Global.System.Drawing.Color
            Get
                Return CType(Me("GUI_ColorPrimary2"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GUI_ColorPrimary2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LightGray")>  _
        Public Property GUI_ShadowColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GUI_ShadowColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GUI_ShadowColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property GUI_ShadowColorSelected() As Global.System.Drawing.Color
            Get
                Return CType(Me("GUI_ShadowColorSelected"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GUI_ShadowColorSelected") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property GUI_ShadowSize() As Integer
            Get
                Return CType(Me("GUI_ShadowSize"),Integer)
            End Get
            Set
                Me("GUI_ShadowSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property GUI_PrimaryForecolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GUI_PrimaryForecolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GUI_PrimaryForecolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DarkGray")>  _
        Public Property GUI_PrimaryForecolorDisabled() As Global.System.Drawing.Color
            Get
                Return CType(Me("GUI_PrimaryForecolorDisabled"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GUI_PrimaryForecolorDisabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property BLL_JobID() As Integer
            Get
                Return CType(Me("BLL_JobID"),Integer)
            End Get
            Set
                Me("BLL_JobID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property BLL_LanguageID() As Integer
            Get
                Return CType(Me("BLL_LanguageID"),Integer)
            End Get
            Set
                Me("BLL_LanguageID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property F_Vision() As Boolean
            Get
                Return CType(Me("F_Vision"),Boolean)
            End Get
            Set
                Me("F_Vision") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property F_RegisterControl() As Boolean
            Get
                Return CType(Me("F_RegisterControl"),Boolean)
            End Get
            Set
                Me("F_RegisterControl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property F_ViscosityControl() As Boolean
            Get
                Return CType(Me("F_ViscosityControl"),Boolean)
            End Get
            Set
                Me("F_ViscosityControl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property GUI_ColorTextbox() As Global.System.Drawing.Color
            Get
                Return CType(Me("GUI_ColorTextbox"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GUI_ColorTextbox") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DSJob.xml")>  _
        Public ReadOnly Property BLL_DSJobFilename() As String
            Get
                Return CType(Me("BLL_DSJobFilename"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DSNavigation.xml")>  _
        Public ReadOnly Property BLL_DSNavigationFilename() As String
            Get
                Return CType(Me("BLL_DSNavigationFilename"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property BLL_ViscosityPause() As Short
            Get
                Return CType(Me("BLL_ViscosityPause"),Short)
            End Get
            Set
                Me("BLL_ViscosityPause") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property F_DensityControl() As Boolean
            Get
                Return CType(Me("F_DensityControl"),Boolean)
            End Get
            Set
                Me("F_DensityControl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property N_Debug() As Boolean
            Get
                Return CType(Me("N_Debug"),Boolean)
            End Get
            Set
                Me("N_Debug") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Zelo.Luma.My.MySettings
            Get
                Return Global.Zelo.Luma.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
