'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class English
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zelo.Luma.English", GetType(English).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Active.
    '''</summary>
    Friend Shared ReadOnly Property strActive() As String
        Get
            Return ResourceManager.GetString("strActive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Actual.
    '''</summary>
    Friend Shared ReadOnly Property strActual() As String
        Get
            Return ResourceManager.GetString("strActual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Allarms Bounds.
    '''</summary>
    Friend Shared ReadOnly Property strAllarmsBound() As String
        Get
            Return ResourceManager.GetString("strAllarmsBound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Allarm Duration.
    '''</summary>
    Friend Shared ReadOnly Property strAllarmTime() As String
        Get
            Return ResourceManager.GetString("strAllarmTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Auto.
    '''</summary>
    Friend Shared ReadOnly Property strAutomatic() As String
        Get
            Return ResourceManager.GetString("strAutomatic", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Average Window.
    '''</summary>
    Friend Shared ReadOnly Property strAverageWindow() As String
        Get
            Return ResourceManager.GetString("strAverageWindow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Back.
    '''</summary>
    Friend Shared ReadOnly Property strBack() As String
        Get
            Return ResourceManager.GetString("strBack", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Base Color.
    '''</summary>
    Friend Shared ReadOnly Property strBaseColor() As String
        Get
            Return ResourceManager.GetString("strBaseColor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Base Settings.
    '''</summary>
    Friend Shared ReadOnly Property strBaseSettings() As String
        Get
            Return ResourceManager.GetString("strBaseSettings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Calibration Real Values.
    '''</summary>
    Friend Shared ReadOnly Property strCalibrationRealValues() As String
        Get
            Return ResourceManager.GetString("strCalibrationRealValues", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cleaning.
    '''</summary>
    Friend Shared ReadOnly Property strCleaning() As String
        Get
            Return ResourceManager.GetString("strCleaning", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Client.
    '''</summary>
    Friend Shared ReadOnly Property strClient() As String
        Get
            Return ResourceManager.GetString("strClient", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Color.
    '''</summary>
    Friend Shared ReadOnly Property strColor() As String
        Get
            Return ResourceManager.GetString("strColor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Copy.
    '''</summary>
    Friend Shared ReadOnly Property strCopy() As String
        Get
            Return ResourceManager.GetString("strCopy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJob() As String
        Get
            Return ResourceManager.GetString("strCurrentJob", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job -base settings-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobBaseSetting() As String
        Get
            Return ResourceManager.GetString("strCurrentJobBaseSetting", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job -copy-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobCopy() As String
        Get
            Return ResourceManager.GetString("strCurrentJobCopy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job -load-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobLoad() As String
        Get
            Return ResourceManager.GetString("strCurrentJobLoad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job -new-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobNew() As String
        Get
            Return ResourceManager.GetString("strCurrentJobNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job -parameter-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobParameter() As String
        Get
            Return ResourceManager.GetString("strCurrentJobParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job -register control-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobRegisterControl() As String
        Get
            Return ResourceManager.GetString("strCurrentJobRegisterControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job -register and viscosity control-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobRegisterViscosityControl() As String
        Get
            Return ResourceManager.GetString("strCurrentJobRegisterViscosityControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job -viscosity control-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobViscosityControl() As String
        Get
            Return ResourceManager.GetString("strCurrentJobViscosityControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Job -vision-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobVision() As String
        Get
            Return ResourceManager.GetString("strCurrentJobVision", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cyclic.
    '''</summary>
    Friend Shared ReadOnly Property strCyclic() As String
        Get
            Return ResourceManager.GetString("strCyclic", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Date Created.
    '''</summary>
    Friend Shared ReadOnly Property strDateCreated() As String
        Get
            Return ResourceManager.GetString("strDateCreated", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Date Modified.
    '''</summary>
    Friend Shared ReadOnly Property strDateModified() As String
        Get
            Return ResourceManager.GetString("strDateModified", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Home.
    '''</summary>
    Friend Shared ReadOnly Property strHome() As String
        Get
            Return ResourceManager.GetString("strHome", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ideal.
    '''</summary>
    Friend Shared ReadOnly Property strIdeal() As String
        Get
            Return ResourceManager.GetString("strIdeal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ideal Temperature.
    '''</summary>
    Friend Shared ReadOnly Property strIdealTemperature() As String
        Get
            Return ResourceManager.GetString("strIdealTemperature", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ideal Viscosity.
    '''</summary>
    Friend Shared ReadOnly Property strIdealViscosity() As String
        Get
            Return ResourceManager.GetString("strIdealViscosity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ink.
    '''</summary>
    Friend Shared ReadOnly Property strInk() As String
        Get
            Return ResourceManager.GetString("strInk", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Intermeasure Time.
    '''</summary>
    Friend Shared ReadOnly Property strIntermeasureTime() As String
        Get
            Return ResourceManager.GetString("strIntermeasureTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage() As String
        Get
            Return ResourceManager.GetString("strLanguage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Italiano.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage1() As String
        Get
            Return ResourceManager.GetString("strLanguage1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to English.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage2() As String
        Get
            Return ResourceManager.GetString("strLanguage2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 3.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage3() As String
        Get
            Return ResourceManager.GetString("strLanguage3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 4.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage4() As String
        Get
            Return ResourceManager.GetString("strLanguage4", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 5.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage5() As String
        Get
            Return ResourceManager.GetString("strLanguage5", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 6.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage6() As String
        Get
            Return ResourceManager.GetString("strLanguage6", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 7.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage7() As String
        Get
            Return ResourceManager.GetString("strLanguage7", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 8.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage8() As String
        Get
            Return ResourceManager.GetString("strLanguage8", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lateral.
    '''</summary>
    Friend Shared ReadOnly Property strLateral() As String
        Get
            Return ResourceManager.GetString("strLateral", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lateral Active.
    '''</summary>
    Friend Shared ReadOnly Property strLateralActive() As String
        Get
            Return ResourceManager.GetString("strLateralActive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lateral Gain.
    '''</summary>
    Friend Shared ReadOnly Property strLateralGain() As String
        Get
            Return ResourceManager.GetString("strLateralGain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Load.
    '''</summary>
    Friend Shared ReadOnly Property strLoad() As String
        Get
            Return ResourceManager.GetString("strLoad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Longitudinal.
    '''</summary>
    Friend Shared ReadOnly Property strLongitudinal() As String
        Get
            Return ResourceManager.GetString("strLongitudinal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Longitudinal Active.
    '''</summary>
    Friend Shared ReadOnly Property strLongitudinalActive() As String
        Get
            Return ResourceManager.GetString("strLongitudinalActive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to LongitudinalGain.
    '''</summary>
    Friend Shared ReadOnly Property strLongitudinalGain() As String
        Get
            Return ResourceManager.GetString("strLongitudinalGain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Manual.
    '''</summary>
    Friend Shared ReadOnly Property strManual() As String
        Get
            Return ResourceManager.GetString("strManual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mark Index.
    '''</summary>
    Friend Shared ReadOnly Property strMarkNumber() As String
        Get
            Return ResourceManager.GetString("strMarkNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mark Positions.
    '''</summary>
    Friend Shared ReadOnly Property strMarkPositions() As String
        Get
            Return ResourceManager.GetString("strMarkPositions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Maximum Correction.
    '''</summary>
    Friend Shared ReadOnly Property strMaximumCorrection() As String
        Get
            Return ResourceManager.GetString("strMaximumCorrection", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Measure Timeout.
    '''</summary>
    Friend Shared ReadOnly Property strMeasureTimeout() As String
        Get
            Return ResourceManager.GetString("strMeasureTimeout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Menù.
    '''</summary>
    Friend Shared ReadOnly Property strMenu() As String
        Get
            Return ResourceManager.GetString("strMenu", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Minimum Correction.
    '''</summary>
    Friend Shared ReadOnly Property strMinimumCorrection() As String
        Get
            Return ResourceManager.GetString("strMinimumCorrection", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mode.
    '''</summary>
    Friend Shared ReadOnly Property strMode() As String
        Get
            Return ResourceManager.GetString("strMode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to New.
    '''</summary>
    Friend Shared ReadOnly Property strNew() As String
        Get
            Return ResourceManager.GetString("strNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Off.
    '''</summary>
    Friend Shared ReadOnly Property strOffColor() As String
        Get
            Return ResourceManager.GetString("strOffColor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Parameter.
    '''</summary>
    Friend Shared ReadOnly Property strParameter() As String
        Get
            Return ResourceManager.GetString("strParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Pause Duration.
    '''</summary>
    Friend Shared ReadOnly Property strPauseTime() As String
        Get
            Return ResourceManager.GetString("strPauseTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Group.
    '''</summary>
    Friend Shared ReadOnly Property strPrintingGroup() As String
        Get
            Return ResourceManager.GetString("strPrintingGroup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Printing Side.
    '''</summary>
    Friend Shared ReadOnly Property strPrintingSide() As String
        Get
            Return ResourceManager.GetString("strPrintingSide", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Back.
    '''</summary>
    Friend Shared ReadOnly Property strPrintingSideBack() As String
        Get
            Return ResourceManager.GetString("strPrintingSideBack", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Front.
    '''</summary>
    Friend Shared ReadOnly Property strPrintingSideFront() As String
        Get
            Return ResourceManager.GetString("strPrintingSideFront", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Project.
    '''</summary>
    Friend Shared ReadOnly Property strProject() As String
        Get
            Return ResourceManager.GetString("strProject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Real Temperature.
    '''</summary>
    Friend Shared ReadOnly Property strRealTemperature() As String
        Get
            Return ResourceManager.GetString("strRealTemperature", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Real Viscosity.
    '''</summary>
    Friend Shared ReadOnly Property strRealViscosity() As String
        Get
            Return ResourceManager.GetString("strRealViscosity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Register Control.
    '''</summary>
    Friend Shared ReadOnly Property strRegisterControl() As String
        Get
            Return ResourceManager.GetString("strRegisterControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Register Parameter.
    '''</summary>
    Friend Shared ReadOnly Property strRegisterParameter() As String
        Get
            Return ResourceManager.GetString("strRegisterParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Register and Viscosity Control.
    '''</summary>
    Friend Shared ReadOnly Property strRegisterViscosityControl() As String
        Get
            Return ResourceManager.GetString("strRegisterViscosityControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SelectMarkIndex.
    '''</summary>
    Friend Shared ReadOnly Property strSelectMarkNumber() As String
        Get
            Return ResourceManager.GetString("strSelectMarkNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Solvent.
    '''</summary>
    Friend Shared ReadOnly Property strSolvent() As String
        Get
            Return ResourceManager.GetString("strSolvent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Solvent Gain.
    '''</summary>
    Friend Shared ReadOnly Property strSolventGain() As String
        Get
            Return ResourceManager.GetString("strSolventGain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System.
    '''</summary>
    Friend Shared ReadOnly Property strSystem() As String
        Get
            Return ResourceManager.GetString("strSystem", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System -configuration-.
    '''</summary>
    Friend Shared ReadOnly Property strSystemConfiguration() As String
        Get
            Return ResourceManager.GetString("strSystemConfiguration", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Temperature.
    '''</summary>
    Friend Shared ReadOnly Property strTemperature() As String
        Get
            Return ResourceManager.GetString("strTemperature", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Viscosity.
    '''</summary>
    Friend Shared ReadOnly Property strViscosity() As String
        Get
            Return ResourceManager.GetString("strViscosity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Viscosity Control.
    '''</summary>
    Friend Shared ReadOnly Property strViscosityControl() As String
        Get
            Return ResourceManager.GetString("strViscosityControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Viscosity Parameter.
    '''</summary>
    Friend Shared ReadOnly Property strViscosityParameter() As String
        Get
            Return ResourceManager.GetString("strViscosityParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vision.
    '''</summary>
    Friend Shared ReadOnly Property strVision() As String
        Get
            Return ResourceManager.GetString("strVision", resourceCulture)
        End Get
    End Property
End Class
