'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Italian
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zelo.Luma.Italian", GetType(Italian).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Attivo.
    '''</summary>
    Friend Shared ReadOnly Property strActive() As String
        Get
            Return ResourceManager.GetString("strActive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Attuale.
    '''</summary>
    Friend Shared ReadOnly Property strActual() As String
        Get
            Return ResourceManager.GetString("strActual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Soglie d&apos;allarme.
    '''</summary>
    Friend Shared ReadOnly Property strAllarmsBound() As String
        Get
            Return ResourceManager.GetString("strAllarmsBound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Durata allarme.
    '''</summary>
    Friend Shared ReadOnly Property strAllarmTime() As String
        Get
            Return ResourceManager.GetString("strAllarmTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Auto.
    '''</summary>
    Friend Shared ReadOnly Property strAutomatic() As String
        Get
            Return ResourceManager.GetString("strAutomatic", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Numero Misurazione.
    '''</summary>
    Friend Shared ReadOnly Property strAverageWindow() As String
        Get
            Return ResourceManager.GetString("strAverageWindow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Indietro.
    '''</summary>
    Friend Shared ReadOnly Property strBack() As String
        Get
            Return ResourceManager.GetString("strBack", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Colore di Riferimento.
    '''</summary>
    Friend Shared ReadOnly Property strBaseColor() As String
        Get
            Return ResourceManager.GetString("strBaseColor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Impostazioni di base.
    '''</summary>
    Friend Shared ReadOnly Property strBaseSettings() As String
        Get
            Return ResourceManager.GetString("strBaseSettings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Taratura valore reale.
    '''</summary>
    Friend Shared ReadOnly Property strCalibrationRealValues() As String
        Get
            Return ResourceManager.GetString("strCalibrationRealValues", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavaggio.
    '''</summary>
    Friend Shared ReadOnly Property strCleaning() As String
        Get
            Return ResourceManager.GetString("strCleaning", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cliente.
    '''</summary>
    Friend Shared ReadOnly Property strClient() As String
        Get
            Return ResourceManager.GetString("strClient", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Colore.
    '''</summary>
    Friend Shared ReadOnly Property strColor() As String
        Get
            Return ResourceManager.GetString("strColor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Copia.
    '''</summary>
    Friend Shared ReadOnly Property strCopy() As String
        Get
            Return ResourceManager.GetString("strCopy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJob() As String
        Get
            Return ResourceManager.GetString("strCurrentJob", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente -impostazioni di base-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobBaseSetting() As String
        Get
            Return ResourceManager.GetString("strCurrentJobBaseSetting", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente -copia-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobCopy() As String
        Get
            Return ResourceManager.GetString("strCurrentJobCopy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente -carica-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobLoad() As String
        Get
            Return ResourceManager.GetString("strCurrentJobLoad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente -nuovo-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobNew() As String
        Get
            Return ResourceManager.GetString("strCurrentJobNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente -parametri-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobParameter() As String
        Get
            Return ResourceManager.GetString("strCurrentJobParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente -controllo di registro-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobRegisterControl() As String
        Get
            Return ResourceManager.GetString("strCurrentJobRegisterControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente -controllo di registro e viscostà-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobRegisterViscosityControl() As String
        Get
            Return ResourceManager.GetString("strCurrentJobRegisterViscosityControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente -controllo di viscosità-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobViscosityControl() As String
        Get
            Return ResourceManager.GetString("strCurrentJobViscosityControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lavoro corrente -visione-.
    '''</summary>
    Friend Shared ReadOnly Property strCurrentJobVision() As String
        Get
            Return ResourceManager.GetString("strCurrentJobVision", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ciclico.
    '''</summary>
    Friend Shared ReadOnly Property strCyclic() As String
        Get
            Return ResourceManager.GetString("strCyclic", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Data creazione.
    '''</summary>
    Friend Shared ReadOnly Property strDateCreated() As String
        Get
            Return ResourceManager.GetString("strDateCreated", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Data ultimo utilizzo.
    '''</summary>
    Friend Shared ReadOnly Property strDateModified() As String
        Get
            Return ResourceManager.GetString("strDateModified", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Home.
    '''</summary>
    Friend Shared ReadOnly Property strHome() As String
        Get
            Return ResourceManager.GetString("strHome", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ideale.
    '''</summary>
    Friend Shared ReadOnly Property strIdeal() As String
        Get
            Return ResourceManager.GetString("strIdeal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Temperature ideale.
    '''</summary>
    Friend Shared ReadOnly Property strIdealTemperature() As String
        Get
            Return ResourceManager.GetString("strIdealTemperature", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Viscosità ideale.
    '''</summary>
    Friend Shared ReadOnly Property strIdealViscosity() As String
        Get
            Return ResourceManager.GetString("strIdealViscosity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Inchiostro.
    '''</summary>
    Friend Shared ReadOnly Property strInk() As String
        Get
            Return ResourceManager.GetString("strInk", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tempo intermisuraizone.
    '''</summary>
    Friend Shared ReadOnly Property strIntermeasureTime() As String
        Get
            Return ResourceManager.GetString("strIntermeasureTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lingua.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage() As String
        Get
            Return ResourceManager.GetString("strLanguage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Italiano.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage1() As String
        Get
            Return ResourceManager.GetString("strLanguage1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to English.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage2() As String
        Get
            Return ResourceManager.GetString("strLanguage2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 3.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage3() As String
        Get
            Return ResourceManager.GetString("strLanguage3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 4.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage4() As String
        Get
            Return ResourceManager.GetString("strLanguage4", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 5.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage5() As String
        Get
            Return ResourceManager.GetString("strLanguage5", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 6.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage6() As String
        Get
            Return ResourceManager.GetString("strLanguage6", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 7.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage7() As String
        Get
            Return ResourceManager.GetString("strLanguage7", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Language 8.
    '''</summary>
    Friend Shared ReadOnly Property strLanguage8() As String
        Get
            Return ResourceManager.GetString("strLanguage8", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trasversale.
    '''</summary>
    Friend Shared ReadOnly Property strLateral() As String
        Get
            Return ResourceManager.GetString("strLateral", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trasversale Attivo.
    '''</summary>
    Friend Shared ReadOnly Property strLateralActive() As String
        Get
            Return ResourceManager.GetString("strLateralActive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Guadagno Trasversale.
    '''</summary>
    Friend Shared ReadOnly Property strLateralGain() As String
        Get
            Return ResourceManager.GetString("strLateralGain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Carica.
    '''</summary>
    Friend Shared ReadOnly Property strLoad() As String
        Get
            Return ResourceManager.GetString("strLoad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Longitudinale.
    '''</summary>
    Friend Shared ReadOnly Property strLongitudinal() As String
        Get
            Return ResourceManager.GetString("strLongitudinal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Longitudinale Attivo.
    '''</summary>
    Friend Shared ReadOnly Property strLongitudinalActive() As String
        Get
            Return ResourceManager.GetString("strLongitudinalActive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Guadagno Laterale.
    '''</summary>
    Friend Shared ReadOnly Property strLongitudinalGain() As String
        Get
            Return ResourceManager.GetString("strLongitudinalGain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Manuale.
    '''</summary>
    Friend Shared ReadOnly Property strManual() As String
        Get
            Return ResourceManager.GetString("strManual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Marca.
    '''</summary>
    Friend Shared ReadOnly Property strMarkNumber() As String
        Get
            Return ResourceManager.GetString("strMarkNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Posizione.
    '''</summary>
    Friend Shared ReadOnly Property strMarkPositions() As String
        Get
            Return ResourceManager.GetString("strMarkPositions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Correzione massima.
    '''</summary>
    Friend Shared ReadOnly Property strMaximumCorrection() As String
        Get
            Return ResourceManager.GetString("strMaximumCorrection", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Timeout misurazione.
    '''</summary>
    Friend Shared ReadOnly Property strMeasureTimeout() As String
        Get
            Return ResourceManager.GetString("strMeasureTimeout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Menù.
    '''</summary>
    Friend Shared ReadOnly Property strMenu() As String
        Get
            Return ResourceManager.GetString("strMenu", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Correzione minima.
    '''</summary>
    Friend Shared ReadOnly Property strMinimumCorrection() As String
        Get
            Return ResourceManager.GetString("strMinimumCorrection", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Modo.
    '''</summary>
    Friend Shared ReadOnly Property strMode() As String
        Get
            Return ResourceManager.GetString("strMode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nuovo.
    '''</summary>
    Friend Shared ReadOnly Property strNew() As String
        Get
            Return ResourceManager.GetString("strNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Off.
    '''</summary>
    Friend Shared ReadOnly Property strOffColor() As String
        Get
            Return ResourceManager.GetString("strOffColor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Parametri.
    '''</summary>
    Friend Shared ReadOnly Property strParameter() As String
        Get
            Return ResourceManager.GetString("strParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Durata pausa.
    '''</summary>
    Friend Shared ReadOnly Property strPauseTime() As String
        Get
            Return ResourceManager.GetString("strPauseTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Gruppo.
    '''</summary>
    Friend Shared ReadOnly Property strPrintingGroup() As String
        Get
            Return ResourceManager.GetString("strPrintingGroup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lato di stampa.
    '''</summary>
    Friend Shared ReadOnly Property strPrintingSide() As String
        Get
            Return ResourceManager.GetString("strPrintingSide", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Volta.
    '''</summary>
    Friend Shared ReadOnly Property strPrintingSideBack() As String
        Get
            Return ResourceManager.GetString("strPrintingSideBack", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bianca.
    '''</summary>
    Friend Shared ReadOnly Property strPrintingSideFront() As String
        Get
            Return ResourceManager.GetString("strPrintingSideFront", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Progetto.
    '''</summary>
    Friend Shared ReadOnly Property strProject() As String
        Get
            Return ResourceManager.GetString("strProject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Temperatura Reale.
    '''</summary>
    Friend Shared ReadOnly Property strRealTemperature() As String
        Get
            Return ResourceManager.GetString("strRealTemperature", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Viscosità Reale.
    '''</summary>
    Friend Shared ReadOnly Property strRealViscosity() As String
        Get
            Return ResourceManager.GetString("strRealViscosity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Controllo di registro.
    '''</summary>
    Friend Shared ReadOnly Property strRegisterControl() As String
        Get
            Return ResourceManager.GetString("strRegisterControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Parametri registro.
    '''</summary>
    Friend Shared ReadOnly Property strRegisterParameter() As String
        Get
            Return ResourceManager.GetString("strRegisterParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Controllo di registro e viscosità.
    '''</summary>
    Friend Shared ReadOnly Property strRegisterViscosityControl() As String
        Get
            Return ResourceManager.GetString("strRegisterViscosityControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Selezione numero marca.
    '''</summary>
    Friend Shared ReadOnly Property strSelectMarkNumber() As String
        Get
            Return ResourceManager.GetString("strSelectMarkNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Solvente.
    '''</summary>
    Friend Shared ReadOnly Property strSolvent() As String
        Get
            Return ResourceManager.GetString("strSolvent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Guadagno solvente.
    '''</summary>
    Friend Shared ReadOnly Property strSolventGain() As String
        Get
            Return ResourceManager.GetString("strSolventGain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sistema.
    '''</summary>
    Friend Shared ReadOnly Property strSystem() As String
        Get
            Return ResourceManager.GetString("strSystem", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sistema -configurazione-.
    '''</summary>
    Friend Shared ReadOnly Property strSystemConfiguration() As String
        Get
            Return ResourceManager.GetString("strSystemConfiguration", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Temperatura.
    '''</summary>
    Friend Shared ReadOnly Property strTemperature() As String
        Get
            Return ResourceManager.GetString("strTemperature", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Viscosità.
    '''</summary>
    Friend Shared ReadOnly Property strViscosity() As String
        Get
            Return ResourceManager.GetString("strViscosity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Controllo di viscosità.
    '''</summary>
    Friend Shared ReadOnly Property strViscosityControl() As String
        Get
            Return ResourceManager.GetString("strViscosityControl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Parametri viscosità.
    '''</summary>
    Friend Shared ReadOnly Property strViscosityParameter() As String
        Get
            Return ResourceManager.GetString("strViscosityParameter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Visione.
    '''</summary>
    Friend Shared ReadOnly Property strVision() As String
        Get
            Return ResourceManager.GetString("strVision", resourceCulture)
        End Get
    End Property
End Class
