#ifndef EEPROM_MSG_VALUE_H
	#define EEPROM_MSG_VALUE_H
	
	#ifdef EEPROM_LANGUAGE_0 
		#define MSG_VALUE_SEC "sec."
		#define MSG_VALUE_MSEC "msec."
		#define MSG_VALUE_CELSIUS "celsius"
		#define MSG_VALUE_NO "No"
		#define MSG_VALUE_PH "pH"
		#define MSG_VALUE_YES "Si'"
		#define MSG_VALUE_PAUSE "Pausa"
		#define MSG_VALUE_RESET "Reset"
		#define MSG_VALUE_TIMERS "Tempi"
		#define MSG_VALUE_LANGUAGES "Lingue"
		#define MSG_VALUE_PH_MAX "pH Max"
		#define MSG_VALUE_PH_MIN "pH Min"
		#define MSG_VALUE_RESET_ASK "Reset?"
		#define MSG_VALUE_BOUNDS "Soglie"
		#define MSG_VALUE_DEUTSCH "Deutsch"
		#define MSG_VALUE_ENGLISH "English"
		#define MSG_VALUE_ESPANOL "Espanol"
		#define MSG_VALUE_FRANCAIS "Francais"
		#define MSG_VALUE_GAIN "Guadagni"
		#define MSG_VALUE_ITALIANO "Italiano"
		#define MSG_VALUE_WASHING "Lavaggio"
		#define MSG_VALUE_LANGUAGE_7 "Lingua 7"
		#define MSG_VALUE_LANGUAGE_8 "Lingua 8"
		#define MSG_VALUE_SOLVENT "Solvente"
		#define MSG_VALUE_CALIBRATION "Taratura"
		#define MSG_VALUE_ERROR_00 "Errore 00"
		#define MSG_VALUE_ERROR_01 "Errore 01"
		#define MSG_VALUE_ERROR_02 "Errore 02"
		#define MSG_VALUE_ERROR_03 "Errore 03"
		#define MSG_VALUE_ERROR_04 "Errore 04"
		#define MSG_VALUE_ERROR_05 "Errore 05"
		#define MSG_VALUE_ERROR_06 "Errore 06"
		#define MSG_VALUE_ERROR_07 "Errore 07"
		#define MSG_VALUE_ERROR_08 "Errore 08"
		#define MSG_VALUE_ERROR_09 "Errore 09"
		#define MSG_VALUE_ERROR_10 "Errore 10"
		#define MSG_VALUE_ERROR_11 "Errore 11"
		#define MSG_VALUE_ERROR_12 "Errore 12"
		#define MSG_VALUE_ERROR_13 "Errore 13"
		#define MSG_VALUE_ERROR_14 "Errore 14"
		#define MSG_VALUE_ERROR_15 "Errore 15"
		#define MSG_VALUE_PARAMETERS "Parametri"
		#define MSG_VALUE_PORTUGUES "Portugues"
		#define MSG_VALUE_VISCOSITY "Viscosita"
		#define MSG_VALUE_ACIDBASE "Acido-Base"
		#define MSG_VALUE_TEMPERATURE "Temperatura"
		#define MSG_VALUE_ENABLE_PH_ASK "Attivare pH?"
		#define MSG_VALUE_SAVE_JOB "Salva Lavoro"
		#define MSG_VALUE_LOAD_JOB "Carica Lavoro"
		#define MSG_VALUE_CONFIGURATION "Installazione"
		#define MSG_VALUE_PH_TOO_DIFFERENT "pH irregolare"
		#define MSG_VALUE_MAX_CORRECTION "Correzione Max"
		#define MSG_VALUE_MIN_CORRECTION "Correzione Min"
		#define MSG_VALUE_MAX_VISCOSITY "Viscosita' Max"
		#define MSG_VALUE_MIN_VISCOSITY "Viscosita' Min"
		#define MSG_VALUE_ALLARM "Allarme"
		#define MSG_VALUE_PH_ONOFF "Abilitazione pH"
		#define MSG_VALUE_JOB_SAVED "Lavoro Salvato"
		#define MSG_VALUE_JOB_LOADED "Lavoro Caricato"
		#define MSG_VALUE_SOLVENT_ASK "Aggiungere"
		#define MSG_VALUE_SOLVENT_ASK2 "Solvente?"
		#define MSG_VALUE_ACIDBASE_ASK "Aggiungere"
		#define MSG_VALUE_ACIDBASE_ASK2 "Acido-Base?"
		#define MSG_VALUE_MAX_TEMPERATURE "Temperatura Max"
		#define MSG_VALUE_MIN_TEMPERATURE "Temperatura Min"
		#define MSG_VALUE_ADDING_SOLVENT3 "in corso"
		#define MSG_VALUE_ADDING_ACIDBASE3 "in corso"
		#define MSG_VALUE_POMP_ON "Pompa Accesa"
		
		
		#define MSG_VALUE_ADDING_SOLVENT2 "Aggiunta Solvente"
		#define MSG_VALUE_ADDING_ACIDBASE2 "Aggiunta Acido-Base"
		#define MSG_VALUE_GENERIC_ERROR "Errore Generico"
		#define MSG_VALUE_OUT_OF_BOUNDS "Fuori limite"
		#define MSG_VALUE_VALVES_DELAY "Ritardi Valvole"
		#define MSG_VALUE_INTERMEASURING "InterMisurazione"
		#define MSG_VALUE_ADDING_SOLVENT "Aggiunta Solvente"
		#define MSG_VALUE_PARAMETER_SAVED "Parametro salvato"
		#define MSG_VALUE_TOO_DIFFERENT "Irregolare"
		#define MSG_VALUE_TIMEOUT_MEASURE "Timeout Misurazione"
		#define MSG_VALUE_WASHING_ASK "Effettuare Lavaggio?"
		#define MSG_VALUE_MEASURING "Misurazione"
		#define MSG_VALUE_CONTACT_YOUR_PROVIDER "Contattare il fornitore"
		#define MSG_VALUE_PRESS_ANY_KEY_TO_STOP "Premere un tasto per terminare"
		#define MSG_VALUE_PRESS_ANY_KEY_TO_CONTINUE "Premere un tasto per continuare"

	#endif
	
	

	#ifdef EEPROM_LANGUAGE_1 
		#define MSG_VALUE_SEC "sec."
		#define MSG_VALUE_MSEC "msec."
		#define MSG_VALUE_CELSIUS "celsius"
		#define MSG_VALUE_NO "No"
		#define MSG_VALUE_PH "pH"
		#define MSG_VALUE_YES "Yes"
		#define MSG_VALUE_PAUSE "Pause"
		#define MSG_VALUE_RESET "Reset"
		#define MSG_VALUE_TIMERS "Timers"
		#define MSG_VALUE_LANGUAGES "Languages"
		#define MSG_VALUE_PH_MAX "pH Max"
		#define MSG_VALUE_PH_MIN "pH Min"
		#define MSG_VALUE_RESET_ASK "Reset?"
		#define MSG_VALUE_BOUNDS "Bounds"
		#define MSG_VALUE_DEUTSCH "Deutsch"
		#define MSG_VALUE_ENGLISH "English"
		#define MSG_VALUE_ESPANOL "Espanol"
		#define MSG_VALUE_FRANCAIS "Francais"
		#define MSG_VALUE_GAIN "Gain"
		#define MSG_VALUE_ITALIANO "Italiano"
		#define MSG_VALUE_WASHING "Washing"
		#define MSG_VALUE_LANGUAGE_7 "Language 7"
		#define MSG_VALUE_LANGUAGE_8 "Language 8"
		#define MSG_VALUE_SOLVENT "Solvent"
		#define MSG_VALUE_CALIBRATION "Calibration"
		#define MSG_VALUE_ERROR_00 "Error 00"
		#define MSG_VALUE_ERROR_01 "Error 01"
		#define MSG_VALUE_ERROR_02 "Error 02"
		#define MSG_VALUE_ERROR_03 "Error 03"
		#define MSG_VALUE_ERROR_04 "Error 04"
		#define MSG_VALUE_ERROR_05 "Error 05"
		#define MSG_VALUE_ERROR_06 "Error 06"
		#define MSG_VALUE_ERROR_07 "Error 07"
		#define MSG_VALUE_ERROR_08 "Error 08"
		#define MSG_VALUE_ERROR_09 "Error 09"
		#define MSG_VALUE_ERROR_10 "Error 10"
		#define MSG_VALUE_ERROR_11 "Error 11"
		#define MSG_VALUE_ERROR_12 "Error 12"
		#define MSG_VALUE_ERROR_13 "Error 13"
		#define MSG_VALUE_ERROR_14 "Error 14"
		#define MSG_VALUE_ERROR_15 "Error 15"
		#define MSG_VALUE_PARAMETERS "Parameters"
		#define MSG_VALUE_PORTUGUES "Portugues"
		#define MSG_VALUE_VISCOSITY "Viscosity"
		#define MSG_VALUE_ACIDBASE "Acid-Base"
		#define MSG_VALUE_TEMPERATURE "Temperature"
		#define MSG_VALUE_ENABLE_PH_ASK "Enable pH?"
		#define MSG_VALUE_SAVE_JOB "Save Job"
		#define MSG_VALUE_LOAD_JOB "Load Job"
		#define MSG_VALUE_CONFIGURATION "Configuration"
		#define MSG_VALUE_PH_TOO_DIFFERENT "pH too different"
		#define MSG_VALUE_MAX_CORRECTION "Max Correction"
		#define MSG_VALUE_MIN_CORRECTION "Min Correction"
		#define MSG_VALUE_MAX_VISCOSITY "Max Viscosity"
		#define MSG_VALUE_MIN_VISCOSITY "Min Viscosity"
		#define MSG_VALUE_ALLARM "Allarm"
		#define MSG_VALUE_PH_ONOFF "pH On-Off"
		#define MSG_VALUE_JOB_SAVED "Job Saved"
		#define MSG_VALUE_JOB_LOADED "Job Loaded"
		#define MSG_VALUE_SOLVENT_ASK "Adding"
		#define MSG_VALUE_SOLVENT_ASK2 "Solvent?"
		#define MSG_VALUE_ACIDBASE_ASK "Adding"
		#define MSG_VALUE_ACIDBASE_ASK2 "Acid-Base?"
		#define MSG_VALUE_MAX_TEMPERATURE "Max Temperature"
		#define MSG_VALUE_MIN_TEMPERATURE "Min Temperature"
		#define MSG_VALUE_ADDING_SOLVENT3 "Solvent"
		#define MSG_VALUE_ADDING_ACIDBASE3 "Acid-Base"
		#define MSG_VALUE_POMP_ON "Pomp On"
		
		
		#define MSG_VALUE_ADDING_SOLVENT2 "Adding"
		#define MSG_VALUE_ADDING_ACIDBASE2 "Adding"
		#define MSG_VALUE_GENERIC_ERROR "Generic Error"
		#define MSG_VALUE_OUT_OF_BOUNDS "Out of bounds"
		#define MSG_VALUE_VALVES_DELAY "Valves delay"
		#define MSG_VALUE_INTERMEASURING "Inter-Measuring"
		#define MSG_VALUE_ADDING_SOLVENT "Adding Solvent"
		#define MSG_VALUE_PARAMETER_SAVED "Parameter saved"
		#define MSG_VALUE_TOO_DIFFERENT "Too different"
		#define MSG_VALUE_TIMEOUT_MEASURE "Timeout measure"
		#define MSG_VALUE_WASHING_ASK "Washing?"
		#define MSG_VALUE_MEASURING "Measuring"
		#define MSG_VALUE_CONTACT_YOUR_PROVIDER "Contact your provider"
		#define MSG_VALUE_PRESS_ANY_KEY_TO_STOP "Press any key to stop"
		#define MSG_VALUE_PRESS_ANY_KEY_TO_CONTINUE "Press any key to continue"

	#endif
	
	#ifdef EEPROM_LANGUAGE_2
		#define MSG_VALUE_SEC "sek."
		#define MSG_VALUE_MSEC "msek."
		#define MSG_VALUE_CELSIUS "celsius"
		#define MSG_VALUE_NO "Keine "
		#define MSG_VALUE_PH "pH"
		#define MSG_VALUE_YES "Ja"
		#define MSG_VALUE_PAUSE "Pause"
		#define MSG_VALUE_RESET "Zuruckstellen "
		#define MSG_VALUE_TIMERS "Timer "
		#define MSG_VALUE_LANGUAGES "Sprachen "
		#define MSG_VALUE_PH_MAX "pH Max"
		#define MSG_VALUE_PH_MIN "pH Min"
		#define MSG_VALUE_RESET_ASK "Zuruckstellen? "
		#define MSG_VALUE_BOUNDS "Grenzen "
		#define MSG_VALUE_DEUTSCH "Deutsch"
		#define MSG_VALUE_ENGLISH "English"
		#define MSG_VALUE_ESPANOL "Espanol"
		#define MSG_VALUE_FRANCAIS "Francais"
		#define MSG_VALUE_GAIN "Gewinn "
		#define MSG_VALUE_ITALIANO "Italiano"
		#define MSG_VALUE_WASHING "Reinigung "
		#define MSG_VALUE_LANGUAGE_7 "Sprache 7 "
		#define MSG_VALUE_LANGUAGE_8 "Sprache 8"
		#define MSG_VALUE_SOLVENT "Losungsmittel "
		#define MSG_VALUE_CALIBRATION "Kalibrierung "
		#define MSG_VALUE_ERROR_00 "Storung 00"
		#define MSG_VALUE_ERROR_01 "Storung 01"
		#define MSG_VALUE_ERROR_02 "Storung 02"
		#define MSG_VALUE_ERROR_03 "Storung 03"
		#define MSG_VALUE_ERROR_04 "Storung 04"
		#define MSG_VALUE_ERROR_05 "Storung 05"
		#define MSG_VALUE_ERROR_06 "Storung 06"
		#define MSG_VALUE_ERROR_07 "Storung 07"
		#define MSG_VALUE_ERROR_08 "Storung 08"
		#define MSG_VALUE_ERROR_09 "Storung 09"
		#define MSG_VALUE_ERROR_10 "Storung 10"
		#define MSG_VALUE_ERROR_11 "Storung 11"
		#define MSG_VALUE_ERROR_12 "Storung 12"
		#define MSG_VALUE_ERROR_13 "Storung 13"
		#define MSG_VALUE_ERROR_14 "Storung 14"
		#define MSG_VALUE_ERROR_15 "Storung 15"
		#define MSG_VALUE_PARAMETERS "Parameter "
		#define MSG_VALUE_PORTUGUES "Portugues"
		#define MSG_VALUE_VISCOSITY "Viskositat"
		#define MSG_VALUE_ACIDBASE "Saure-Unterseite "
		#define MSG_VALUE_TEMPERATURE "Temperatur "
		#define MSG_VALUE_ENABLE_PH_ASK "Ermoglichen pH?"
		#define MSG_VALUE_SAVE_JOB "Ausser Job "
		#define MSG_VALUE_LOAD_JOB "LastscJob "
		#define MSG_VALUE_CONFIGURATION "Konfiguration "
		#define MSG_VALUE_PH_TOO_DIFFERENT "pH zu unterschiedlich "
		#define MSG_VALUE_MAX_CORRECTION "Max Korrektur "
		#define MSG_VALUE_MIN_CORRECTION "Min Korrektur "
		#define MSG_VALUE_MAX_VISCOSITY "Max Viskositat"
		#define MSG_VALUE_MIN_VISCOSITY "Min Viskositat"
		#define MSG_VALUE_ALLARM "Allarm"
		#define MSG_VALUE_PH_ONOFF "pH Ein-Aus "
		#define MSG_VALUE_JOB_SAVED "Job gespeichert "
		#define MSG_VALUE_JOB_LOADED "Job geladen "
		#define MSG_VALUE_SOLVENT_ASK "Addieren Des"
		#define MSG_VALUE_SOLVENT_ASK2 "Losungsmittels? "
		#define MSG_VALUE_ACIDBASE_ASK "Addieren Der"
		#define MSG_VALUE_ACIDBASE_ASK2 "Saure-Unterseite? "
		#define MSG_VALUE_MAX_TEMPERATURE "Max Temperatur "
		#define MSG_VALUE_MIN_TEMPERATURE "Min Temperatur "
		#define MSG_VALUE_ADDING_SOLVENT3 "Losungsmittels"
		#define MSG_VALUE_ADDING_ACIDBASE3 "Saure-Unterseite"
		#define MSG_VALUE_POMP_ON "Pumpe auf"
		
		
		#define MSG_VALUE_ADDING_SOLVENT2 "Addieren Des"
		#define MSG_VALUE_ADDING_ACIDBASE2 "Addieren Der "
		#define MSG_VALUE_GENERIC_ERROR "Generische Störung "
		#define MSG_VALUE_OUT_OF_BOUNDS "aus Grenzen heraus"
		#define MSG_VALUE_VALVES_DELAY "Ventile verzogert "
		#define MSG_VALUE_INTERMEASURING "Zwischen-Messen "
		#define MSG_VALUE_ADDING_SOLVENT "Addieren Des Lösungsmittels "
		#define MSG_VALUE_PARAMETER_SAVED "Parameter speicherte "
		#define MSG_VALUE_TOO_DIFFERENT "zu unterschiedlich"
		#define MSG_VALUE_TIMEOUT_MEASURE "Abschaltung Mass"
		#define MSG_VALUE_WASHING_ASK "Reinigung? "
		#define MSG_VALUE_MEASURING "Messende"
		#define MSG_VALUE_CONTACT_YOUR_PROVIDER "Treten Sie mit Ihrem Lieferanten in Verbindung "
		#define MSG_VALUE_PRESS_ANY_KEY_TO_STOP "Betätigen Sie jeden möglichen Schlüssel, um zu stoppen "
		#define MSG_VALUE_PRESS_ANY_KEY_TO_CONTINUE "Betätigen Sie jeden möglichen Schlüssel, um fortzufahren "

	#endif
	
#endif